[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "src"
authors = [{name = "Alexandre MATHIEU", email = "alexandre.mathieu@cstb.fr"}]
version = "0.1.0"
description = "Project information"
